# Generated by Django 4.0.4 on 2022-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=20)),
                ('LName', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
