# Generated by Django 4.0.4 on 2022-05-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=12)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login_Details',
        ),
    ]
